"""added invoices table

Revision ID: 7aac20cccc93
Revises: de79071ba9c2
Create Date: 2022-04-15 13:24:48.638462

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '7aac20cccc93'
down_revision = 'de79071ba9c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invoices',
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('invoice_number', sa.String(length=63), nullable=True),
    sa.Column('release_time', sa.DateTime(), nullable=True),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.order_id'], ),
    sa.PrimaryKeyConstraint('invoice_id'),
    sa.UniqueConstraint('invoice_number'),
    sa.UniqueConstraint('order_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('invoices')
    # ### end Alembic commands ###
